name: Dylan Staley
markdown: redcarpet
highlighter: pygments
description: "The blog and portfolio of Dylan Staley."
domain: dstaley.me
url: "http://dstaley.me"
exclude: ['Gemfile', 's3_website.yml']
sass:
  sass_dir: css
  style: :compressed